name: sv_somatic_cns
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - delly==1.1.3
  - manta==1.6.0
  - svaba==1.1.0
  - survivor==1.0.7
  - bcftools==1.15.1
  - samtools==1.15.1