name: sv_somatic_cns_R
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - bioconductor-genomicalignments==1.30.0
  - r-tidyverse==1.3.2
  - r-data.table==1.14.2
  - r-readxl==1.4.1
  - r-optparse==1.7.3
  - bioconductor-rtracklayer==1.54.0
